# worker/wrangler.toml
#
# رابط الكتب الفعلي بعد النشر:
#   https://alf-bab.hasankoyjd2.workers.dev/6.zstd

name = "alf-bab"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[r2_buckets]]
binding = "ALFBAB_BUCKET"
bucket_name = "alfbab"
